services:
  - type: web
    name: lemon-shot-game
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: node server.mjs
    envVars:
      - key: NODE_ENV
        value: production
